FROM node

# Build Arguments
ARG DB_URI
ARG NODE_ENV

# Install Server Prerequisites
# RUN npm install -g grunt-cli
# RUN npm install -g bower
RUN npm install -g nodemon
RUN npm install -g node-inspector

# Make everything available for start
WORKDIR /src

# Set environment variables
ENV NODE_ENV $NODE_ENV
ENV DB_URI $DB_URI

# Port 3001 for server
# Port 8080 for debugger
EXPOSE 3001
EXPOSE 8080

# Run application
CMD /bin/bash -c "node-inspector & nodemon -L --debug server.js"
